apiVersion: apps/v1
kind: Deployment
metadata:
  name: myngx
  namespace: myweb
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      nodeSelector:
#        name: localhost.localdomain  #设置成自己的node名称或删除
      containers:
        - name: nginxtest
          image: nginx:1.18-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80